# ML - REGRESION LINEAL REGULARIZADA

In [25]:
import numpy as np
import pandas as pd

## Paso 1: Definicion del problema (target)
Tenemos que elegir nosotros la variable obejtivo

## Paso 2: Recopilacion de datos
[fuente](https://raw.githubusercontent.com/4GeeksAcademy/regularized-linear-regression-project-tutorial/main/demographic_health_data.csv)

### Importamos los datos y creamos el DataFrame

In [43]:
df = pd.read_csv('../data/raw/demographic_health_data.csv', index_col='COUNTY_NAME')
df

,fips,TOT_POP,0-9,0-9 y/o % of total pop,19-Oct,10-19 y/o % of total pop,20-29,20-29 y/o % of total pop,30-39,30-39 y/o % of total pop,...,COPD_number,diabetes_prevalence,diabetes_Lower 95% CI,diabetes_Upper 95% CI,diabetes_number,CKD_prevalence,CKD_Lower 95% CI,CKD_Upper 95% CI,CKD_number,Urban_rural_code
COUNTY_NAME,,,,,,,,,,,,,,,,,,,,,
Autauga,1001,55601,6787,12.206615,7637,13.735364,6878,12.370281,7089,12.749771,...,3644,12.9,11.9,13.8,5462,3.1,2.9,3.3,1326,3
Baldwin,1003,218022,24757,11.355276,26913,12.344167,23579,10.814964,25213,11.564429,...,14692,12.0,11.0,13.1,20520,3.2,3.0,3.5,5479,4
Barbour,1005,24881,2732,10.980266,2960,11.896628,3268,13.134520,3201,12.865239,...,2373,19.7,18.6,20.6,3870,4.5,4.2,4.8,887,6
Bibb,1007,22400,2456,10.964286,2596,11.589286,3029,13.522321,3113,13.897321,...,1789,14.1,13.2,14.9,2511,3.3,3.1,3.6,595,2
Blount,1009,57840,7095,12.266598,7570,13.087828,6742,11.656293,6884,11.901798,...,4661,13.5,12.6,14.5,6017,3.4,3.2,3.7,1507,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sweetwater,56037,43051,6104,14.178532,6326,14.694200,5359,12.448027,6577,15.277229,...,2098,8.9,8.3,9.6,2834,2.6,2.4,2.8,821,5
Teton,56039,23081,2384,10.328842,2185,9.466661,2967,12.854729,4093,17.733200,...,928,7.2,6.5,8.0,1360,2.4,2.2,2.6,447,5
Uinta,56041,20299,3121,15.375142,3205,15.788955,2153,10.606434,2702,13.311001,...,1163,10.4,9.5,11.2,1500,3.0,2.8,3.2,430,5
Washakie,56043,7885,858,10.881420,1113,14.115409,715,9.067850,903,11.452124,...,506,11.3,10.3,12.1,686,3.4,3.2,3.7,207,6
Weston,56045,6967,780,11.195637,779,11.181283,681,9.774652,906,13.004162,...,480,11.7,10.7,12.7,644,3.4,3.1,3.6,185,6

fips,TOT_POP,0-9,0-9 y/o % of total pop,19-Oct,10-19 y/o % of total pop,20-29,20-29 y/o % of total pop,30-39,30-39 y/o % of total pop,40-49,40-49 y/o % of total pop,50-59,50-59 y/o % of total pop,60-69,60-69 y/o % of total pop,70-79,70-79 y/o % of total pop,80+,80+ y/o % of total pop,White-alone pop,% White-alone,Black-alone pop,% Black-alone,Native American/American Indian-alone pop,% NA/AI-alone,Asian-alone pop,% Asian-alone,Hawaiian/Pacific Islander-alone pop,% Hawaiian/PI-alone,Two or more races pop,% Two or more races,POP_ESTIMATE_2018,N_POP_CHG_2018,GQ_ESTIMATES_2018,R_birth_2018,R_death_2018,R_NATURAL_INC_2018,R_INTERNATIONAL_MIG_2018,R_DOMESTIC_MIG_2018,R_NET_MIG_2018,Less than a high school diploma 2014-18,High school diploma only 2014-18,Some college or associate's degree 2014-18,Bachelor's degree or higher 2014-18,Percent of adults with less than a high school diploma 2014-18,Percent of adults with a high school diploma only 2014-18,Percent of adults completing some college or associate's degree 2014-18,Percent of adults with a bachelor's degree or higher 2014-18,POVALL_2018,PCTPOVALL_2018,PCTPOV017_2018,PCTPOV517_2018,MEDHHINC_2018,CI90LBINC_2018,CI90UBINC_2018,Civilian_labor_force_2018,Employed_2018,Unemployed_2018,Unemployment_rate_2018,Median_Household_Income_2018,Med_HH_Income_Percent_of_State_Total_2018,Active Physicians per 100000 Population 2018 (AAMC),Total Active Patient Care Physicians per 100000 Population 2018 (AAMC),Active Primary Care Physicians per 100000 Population 2018 (AAMC),Active Patient Care Primary Care Physicians per 100000 Population 2018 (AAMC),Active General Surgeons per 100000 Population 2018 (AAMC),Active Patient Care General Surgeons per 100000 Population 2018 (AAMC),Total nurse practitioners (2019),Total physician assistants (2019),Total Hospitals (2019),Internal Medicine Primary Care (2019),Family Medicine/General Practice Primary Care (2019),Total Specialist Physicians (2019),ICU Beds_x,Total Population,Population Aged 60+,Percent of Population Aged 60+,COUNTY_NAME,STATE_NAME,STATE_FIPS,CNTY_FIPS,county_pop2018_18 and older,anycondition_prevalence,anycondition_Lower 95% CI,anycondition_Upper 95% CI,anycondition_number,Obesity_prevalence,Obesity_Lower 95% CI,Obesity_Upper 95% CI,Obesity_number,Heart disease_prevalence,Heart disease_Lower 95% CI,Heart disease_Upper 95% CI,Heart disease_number,COPD_prevalence,COPD_Lower 95% CI,COPD_Upper 95% CI,COPD_number,diabetes_prevalence,diabetes_Lower 95% CI,diabetes_Upper 95% CI,diabetes_number,CKD_prevalence,CKD_Lower 95% CI,CKD_Upper 95% CI,CKD_number,Urban_rural_code

In [45]:
df_info_columns = pd.read_csv('/workspaces/pabloaznar-intro-ml/data/raw/data_dict.csv', index_col='Column')
df_info_columns
#df_info_columns.loc['flips']

,description,info
Column,,
fips,FIPS Code for the County,NaN
TOT_POP,Total Population,This data as well as all Age and Race data is ...
0-9,Population aged 0-9,All of the other age columns are the same but ...
0-9 y/o % of total pop,% of the population aged 0-9,NaN
10-19',NaN,NaN
...,...,...
NaN,"7 (Urban population of 2,500 to 19,999, not ad...",NaN
NaN,"8 (Completely rural or less than 2,500 urban p...",NaN
NaN,"9 (Completely rural or less than 2,500 urban p...",NaN
NaN,88 (Unknown-Alaska/Hawaii State/not official U...,NaN
NaN,99 (Unknown/not official USDA Rural-Urban Cont...,NaN

## Paso 3: Realizamos un EDA completo

### Analisis descriptivo

In [7]:
# Obtenemos las dimensiones
df.shape

(3140, 108)

In [46]:
# Obtenemos informacion sobre el tipo de datos y valores no nulos
df.info('Heart disease_prevalence')

<class 'pandas.core.frame.DataFrame'>
Index: 3140 entries, Autauga to Weston
Data columns (total 107 columns):
 #    Column                                                                         Dtype
---   ------                                                                         -----
 0    fips                                                                           int64
 1    TOT_POP                                                                        int64
 2    0-9                                                                            int64
 3    0-9 y/o % of total pop                                                         float64
 4    19-Oct                                                                         int64
 5    10-19 y/o % of total pop                                                       float64
 6    20-29                                                                          int64
 7    20-29 y/o % of total pop                                                       float64
 8    30-39                                                                          int64
 9    30-39 y/o % of total pop                                                       float64
 10   40-49                                                                          int64
 11   40-49 y/o % of total pop                                                       float64
 12   50-59                                                                          int64
 13   50-59 y/o % of total pop                                                       float64
 14   60-69                                                                          int64
 15   60-69 y/o % of total pop                                                       float64
 16   70-79                                                                          int64
 17   70-79 y/o % of total pop                                                       float64
 18   80+                                                                            int64
 19   80+ y/o % of total pop                                                         float64
 20   White-alone pop                                                                int64
 21   % White-alone                                                                  float64
 22   Black-alone pop                                                                int64
 23   % Black-alone                                                                  float64
 24   Native American/American Indian-alone pop                                      int64
 25   % NA/AI-alone                                                                  float64
 26   Asian-alone pop                                                                int64
 27   % Asian-alone                                                                  float64
 28   Hawaiian/Pacific Islander-alone pop                                            int64
 29   % Hawaiian/PI-alone                                                            float64
 30   Two or more races pop                                                          int64
 31   % Two or more races                                                            float64
 32   POP_ESTIMATE_2018                                                              int64
 33   N_POP_CHG_2018                                                                 int64
 34   GQ_ESTIMATES_2018                                                              int64
 35   R_birth_2018                                                                   float64
 36   R_death_2018                                                                   float64
 37   R_NATURAL_INC_2018                                                             float64
 38   R_INTERNATIONAL_MIG_2018                                                       float64
 39   R_DOMESTIC_MIG_2018                                                            float64
 40   R_NET_MIG_2018                                                                 float64
 41   Less than a high school diploma 2014-18                                        int64
 42   High school diploma only 2014-18                                               int64
 43   Some college or associate's degree 2014-18                                     int64
 44   Bachelor's degree or higher 2014-18                                            int64
 45   Percent of adults with less than a high school diploma 2014-18                 float64
 46   Percent of adults with a high school diploma only 2014-18                      float64
 47   Percent of adults completing some college or associate's degree 2014-18        float64
 48   Percent of adults with a bachelor's degree or higher 2014-18                   float64
 49   POVALL_2018                                                                    int64
 50   PCTPOVALL_2018                                                                 float64
 51   PCTPOV017_2018                                                                 float64
 52   PCTPOV517_2018                                                                 float64
 53   MEDHHINC_2018                                                                  int64
 54   CI90LBINC_2018                                                                 int64
 55   CI90UBINC_2018                                                                 int64
 56   Civilian_labor_force_2018                                                      int64
 57   Employed_2018                                                                  int64
 58   Unemployed_2018                                                                int64
 59   Unemployment_rate_2018                                                         float64
 60   Median_Household_Income_2018                                                   int64
 61   Med_HH_Income_Percent_of_State_Total_2018                                      float64
 62   Active Physicians per 100000 Population 2018 (AAMC)                            float64
 63   Total Active Patient Care Physicians per 100000 Population 2018 (AAMC)         float64
 64   Active Primary Care Physicians per 100000 Population 2018 (AAMC)               float64
 65   Active Patient Care Primary Care Physicians per 100000 Population 2018 (AAMC)  float64
 66   Active General Surgeons per 100000 Population 2018 (AAMC)                      float64
 67   Active Patient Care General Surgeons per 100000 Population 2018 (AAMC)         float64
 68   Total nurse practitioners (2019)                                               float64
 69   Total physician assistants (2019)                                              float64
 70   Total Hospitals (2019)                                                         float64
 71   Internal Medicine Primary Care (2019)                                          float64
 72   Family Medicine/General Practice Primary Care (2019)                           float64
 73   Total Specialist Physicians (2019)                                             float64
 74   ICU Beds_x                                                                     int64
 75   Total Population                                                               int64
 76   Population Aged 60+                                                            int64
 77   Percent of Population Aged 60+                                                 float64
 78   STATE_NAME                                                                     object
 79   STATE_FIPS                                                                     int64
 80   CNTY_FIPS                                                                      int64
 81   county_pop2018_18 and older                                                    int64
 82   anycondition_prevalence                                                        float64
 83   anycondition_Lower 95% CI                                                      float64
 84   anycondition_Upper 95% CI                                                      float64
 85   anycondition_number                                                            int64
 86   Obesity_prevalence                                                             float64
 87   Obesity_Lower 95% CI                                                           float64
 88   Obesity_Upper 95% CI                                                           float64
 89   Obesity_number                                                                 int64
 90   Heart disease_prevalence                                                       float64
 91   Heart disease_Lower 95% CI                                                     float64
 92   Heart disease_Upper 95% CI                                                     float64
 93   Heart disease_number                                                           int64
 94   COPD_prevalence                                                                float64
 95   COPD_Lower 95% CI                                                              float64
 96   COPD_Upper 95% CI                                                              float64
 97   COPD_number                                                                    int64
 98   diabetes_prevalence                                                            float64
 99   diabetes_Lower 95% CI                                                          float64
 100  diabetes_Upper 95% CI                                                          float64
 101  diabetes_number                                                                int64
 102  CKD_prevalence                                                                 float64
 103  CKD_Lower 95% CI                                                               float64
 104  CKD_Upper 95% CI                                                               float64
 105  CKD_number                                                                     int64
 106  Urban_rural_code                                                               int64
dtypes: float64(61), int64(45), object(1)
memory usage: 2.6+ MB

In [22]:
# Obtenemos información estadística de las variables numércias
df.describe().T

,count,mean,std,min,25%,50%,75%,max
fips,3140.0,30401.640764,15150.559265,1001.0,18180.500000,29178.000000,45081.50000,5.604500e+04
TOT_POP,3140.0,104189.412420,333583.395432,88.0,10963.250000,25800.500000,67913.00000,1.010552e+07
0-9,3140.0,12740.302866,41807.301846,0.0,1280.500000,3057.000000,8097.00000,1.208253e+06
0-9 y/o % of total pop,3140.0,11.871051,2.124081,0.0,10.594639,11.802727,12.95184,2.546068e+01
19-Oct,3140.0,13367.976752,42284.392134,0.0,1374.500000,3274.000000,8822.25000,1.239139e+06
...,...,...,...,...,...,...,...,...
CKD_prevalence,3140.0,3.446242,0.568059,1.8,3.100000,3.400000,3.80000,6.200000e+00
CKD_Lower 95% CI,3140.0,3.207516,0.527740,1.7,2.900000,3.200000,3.50000,5.800000e+00
CKD_Upper 95% CI,3140.0,3.710478,0.613069,1.9,3.300000,3.700000,4.10000,6.600000e+00
CKD_number,3140.0,2466.234076,7730.422067,3.0,314.750000,718.000000,1776.25000,2.377660e+05
Urban_rural_code,3140.0,4.635350,1.510447,1.0,3.000000,5.000000,6.00000,6.000000e+00

> ## Observaciones:
>
> - Existen un total de 3140 filas (en este caso, condados) y 108 columnas
> - Los datos constan de 106 variables numéricas y 2 categóricas

### Limpieza de datos

In [23]:
# Comprobamos si hay valores duplicados
df[df.duplicated()]

Empty DataFrame
Columns: [fips, TOT_POP, 0-9, 0-9 y/o % of total pop, 19-Oct, 10-19 y/o % of total pop, 20-29, 20-29 y/o % of total pop, 30-39, 30-39 y/o % of total pop, 40-49, 40-49 y/o % of total pop, 50-59, 50-59 y/o % of total pop, 60-69, 60-69 y/o % of total pop, 70-79, 70-79 y/o % of total pop, 80+, 80+ y/o % of total pop, White-alone pop, % White-alone, Black-alone pop, % Black-alone, Native American/American Indian-alone pop, % NA/AI-alone, Asian-alone pop, % Asian-alone, Hawaiian/Pacific Islander-alone pop, % Hawaiian/PI-alone, Two or more races pop, % Two or more races, POP_ESTIMATE_2018, N_POP_CHG_2018, GQ_ESTIMATES_2018, R_birth_2018, R_death_2018, R_NATURAL_INC_2018, R_INTERNATIONAL_MIG_2018, R_DOMESTIC_MIG_2018, R_NET_MIG_2018, Less than a high school diploma 2014-18, High school diploma only 2014-18, Some college or associate's degree 2014-18, Bachelor's degree or higher 2014-18, Percent of adults with less than a high school diploma 2014-18, Percent of adults with a high school diploma only 2014-18, Percent of adults completing some college or associate's degree 2014-18, Percent of adults with a bachelor's degree or higher 2014-18, POVALL_2018, PCTPOVALL_2018, PCTPOV017_2018, PCTPOV517_2018, MEDHHINC_2018, CI90LBINC_2018, CI90UBINC_2018, Civilian_labor_force_2018, Employed_2018, Unemployed_2018, Unemployment_rate_2018, Median_Household_Income_2018, Med_HH_Income_Percent_of_State_Total_2018, Active Physicians per 100000 Population 2018 (AAMC), Total Active Patient Care Physicians per 100000 Population 2018 (AAMC), Active Primary Care Physicians per 100000 Population 2018 (AAMC), Active Patient Care Primary Care Physicians per 100000 Population 2018 (AAMC), Active General Surgeons per 100000 Population 2018 (AAMC), Active Patient Care General Surgeons per 100000 Population 2018 (AAMC), Total nurse practitioners (2019), Total physician assistants (2019), Total Hospitals (2019), Internal Medicine Primary Care (2019), Family Medicine/General Practice Primary Care (2019), Total Specialist Physicians (2019), ICU Beds_x, Total Population, Population Aged 60+, Percent of Population Aged 60+, COUNTY_NAME, STATE_NAME, STATE_FIPS, CNTY_FIPS, county_pop2018_18 and older, anycondition_prevalence, anycondition_Lower 95% CI, anycondition_Upper 95% CI, anycondition_number, Obesity_prevalence, Obesity_Lower 95% CI, Obesity_Upper 95% CI, Obesity_number, Heart disease_prevalence, Heart disease_Lower 95% CI, Heart disease_Upper 95% CI, Heart disease_number, COPD_prevalence, COPD_Lower 95% CI, COPD_Upper 95% CI, COPD_number, diabetes_prevalence, ...]
Index: []

[0 rows x 108 columns]

In [47]:
df

,fips,TOT_POP,0-9,0-9 y/o % of total pop,19-Oct,10-19 y/o % of total pop,20-29,20-29 y/o % of total pop,30-39,30-39 y/o % of total pop,...,COPD_number,diabetes_prevalence,diabetes_Lower 95% CI,diabetes_Upper 95% CI,diabetes_number,CKD_prevalence,CKD_Lower 95% CI,CKD_Upper 95% CI,CKD_number,Urban_rural_code
COUNTY_NAME,,,,,,,,,,,,,,,,,,,,,
Autauga,1001,55601,6787,12.206615,7637,13.735364,6878,12.370281,7089,12.749771,...,3644,12.9,11.9,13.8,5462,3.1,2.9,3.3,1326,3
Baldwin,1003,218022,24757,11.355276,26913,12.344167,23579,10.814964,25213,11.564429,...,14692,12.0,11.0,13.1,20520,3.2,3.0,3.5,5479,4
Barbour,1005,24881,2732,10.980266,2960,11.896628,3268,13.134520,3201,12.865239,...,2373,19.7,18.6,20.6,3870,4.5,4.2,4.8,887,6
Bibb,1007,22400,2456,10.964286,2596,11.589286,3029,13.522321,3113,13.897321,...,1789,14.1,13.2,14.9,2511,3.3,3.1,3.6,595,2
Blount,1009,57840,7095,12.266598,7570,13.087828,6742,11.656293,6884,11.901798,...,4661,13.5,12.6,14.5,6017,3.4,3.2,3.7,1507,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sweetwater,56037,43051,6104,14.178532,6326,14.694200,5359,12.448027,6577,15.277229,...,2098,8.9,8.3,9.6,2834,2.6,2.4,2.8,821,5
Teton,56039,23081,2384,10.328842,2185,9.466661,2967,12.854729,4093,17.733200,...,928,7.2,6.5,8.0,1360,2.4,2.2,2.6,447,5
Uinta,56041,20299,3121,15.375142,3205,15.788955,2153,10.606434,2702,13.311001,...,1163,10.4,9.5,11.2,1500,3.0,2.8,3.2,430,5
Washakie,56043,7885,858,10.881420,1113,14.115409,715,9.067850,903,11.452124,...,506,11.3,10.3,12.1,686,3.4,3.2,3.7,207,6
Weston,56045,6967,780,11.195637,779,11.181283,681,9.774652,906,13.004162,...,480,11.7,10.7,12.7,644,3.4,3.1,3.6,185,6

In [ ]:
df.drop(['0-9', '19-Oct', '20-29'], axis=1, inplace=True)