# ML - NAIVE BAYES

In [35]:
import numpy as np
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import classification_report
from utils1 import get_classifier_metrics

# Paso 1: Carga del conjunto de datos

In [2]:
df = pd.read_csv('../data/raw/playstore_reviews.csv')
df

,package_name,review,polarity
0,com.facebook.katana,privacy at least put some option appear offli...,0
1,com.facebook.katana,"messenger issues ever since the last update, ...",0
2,com.facebook.katana,profile any time my wife or anybody has more ...,0
3,com.facebook.katana,the new features suck for those of us who don...,0
4,com.facebook.katana,forced reload on uploading pic on replying co...,0
...,...,...,...
886,com.rovio.angrybirds,loved it i loooooooooooooovvved it because it...,1
887,com.rovio.angrybirds,all time legendary game the birthday party le...,1
888,com.rovio.angrybirds,ads are way to heavy listen to the bad review...,0
889,com.rovio.angrybirds,fun works perfectly well. ads aren't as annoy...,1
890,com.rovio.angrybirds,they're everywhere i see angry birds everywhe...,1

# Paso 2: Estudio de variables y su contenido

In [3]:
df = df.drop(columns=['package_name'])

In [12]:
df

                                                review  polarity
0    privacy at least put some option appear offlin...         0
1    messenger issues ever since the last update, i...         0
2    profile any time my wife or anybody has more t...         0
3    the new features suck for those of us who don'...         0
4    forced reload on uploading pic on replying com...         0
..                                                 ...       ...
886  loved it i loooooooooooooovvved it because it ...         1
887  all time legendary game the birthday party lev...         1
888  ads are way to heavy listen to the bad reviews...         0
889  fun works perfectly well. ads aren't as annoyi...         1
890  they're everywhere i see angry birds everywher...         1

[891 rows x 2 columns]

In [21]:
df["review"] = df["review"].str.strip().str.lower()  # Eliminamos espacios dobles y convertimos a minusculas

x_nb = df['review']
y_nb = df['polarity']

x_train_nb, x_test_nb, y_train_nb, y_test_nb = train_test_split(x_nb, y_nb, test_size=0.2, random_state=21)

x_test_nb

617    awesome can't be productive without evernote. ...
379    i can't send messages because in my settings i...
725    pop-up and search using image. i seriously hat...
826    greatfull! amazing!surprise! this is the main ...
450    doesn't refresh properly i added a few contact...
                             ...
61     videos and notifications my videos haven't bee...
166    like my review and take my advice i cant save ...
123    either make the moving forward process 3 bars ...
625    best browser in short size i cut 1 star becaus...
847                 good ŕ¤ŕ¤ŕ¤śŕ¤ž ŕ¤°ŕ¤žŕ¤žŕľŕ¤°ŕľ
Name: review, Length: 179, dtype: object

In [22]:
vec_model = CountVectorizer(stop_words = "english")
x_train_nb = vec_model.fit_transform(x_train_nb).toarray()
x_test_nb = vec_model.transform(x_test_nb).toarray()

In [40]:
x_train_nb_df = pd.DataFrame(x_train_nb)

In [13]:
print(x_train_nb[0])   # características de la primera reseña

[0 0 0 ... 0 0 0]

In [16]:
vocabulario = vec_model.get_feature_names_out()
vocabulario

array(['000', '04', '0x', ..., 'žŕľ', 'ˇŕ', 'ˇŕľ'],
      shape=(3275,), dtype=object)

Paso 3: Construimos los modelos de naive bayes

In [23]:
multinomial_nb_model = MultinomialNB()
multinomial_nb_model.fit(x_train_nb, y_train_nb)

MultinomialNB()

In [26]:
y_pred_test = multinomial_nb_model.predict(x_test_nb)
y_pred_train = multinomial_nb_model.predict(x_train_nb)

In [31]:
default_multinomial = get_classifier_metrics(y_pred_test, y_test_nb, y_pred_train, y_train_nb, average='weighted')
default_multinomial

           Accuracy  F1 Score  Precision    Recall
Train set  0.948034  0.947844   0.947860  0.948034
Test set   0.826816  0.823663   0.825115  0.826816

In [32]:
report_multinomial_nb= classification_report(y_test_nb, y_pred_test)
print(report_multinomial_nb)

              precision    recall  f1-score   support

           0       0.84      0.90      0.87       114
           1       0.80      0.69      0.74        65

    accuracy                           0.83       179
   macro avg       0.82      0.80      0.81       179
weighted avg       0.83      0.83      0.82       179

In [36]:
bernoulli_nb_model = BernoulliNB()
bernoulli_nb_model.fit(x_train_nb, y_train_nb)

BernoulliNB()

In [37]:
y_pred_test = bernoulli_nb_model.predict(x_test_nb)
y_pred_train = bernoulli_nb_model.predict(x_train_nb)

In [38]:
default_bernoulli = get_classifier_metrics(y_pred_test, y_test_nb, y_pred_train, y_train_nb, average='weighted')
default_bernoulli

           Accuracy  F1 Score  Precision    Recall
Train set  0.918539  0.915637   0.925838  0.918539
Test set   0.793296  0.777147   0.807682  0.793296

In [39]:
report_bernoulli_nb= classification_report(y_test_nb, y_pred_test)
print(report_bernoulli_nb)

              precision    recall  f1-score   support

           0       0.77      0.96      0.85       114
           1       0.87      0.51      0.64        65

    accuracy                           0.79       179
   macro avg       0.82      0.73      0.75       179
weighted avg       0.81      0.79      0.78       179

In [41]:
gaussian_nb_model = GaussianNB()
gaussian_nb_model.fit(x_train_nb, y_train_nb)

GaussianNB()

In [43]:
y_pred_test_3 = gaussian_nb_model.predict(x_test_nb)
y_pred_train_3 = gaussian_nb_model.predict(x_train_nb)

In [45]:
default_gaussian = get_classifier_metrics(y_pred_test, y_test_nb, y_pred_train, y_train_nb, average='weighted')
default_gaussian

           Accuracy  F1 Score  Precision    Recall
Train set  0.918539  0.915637   0.925838  0.918539
Test set   0.793296  0.777147   0.807682  0.793296

In [46]:
report_gaussian_nb= classification_report(y_test_nb, y_pred_test)
print(report_gaussian_nb)

              precision    recall  f1-score   support

           0       0.77      0.96      0.85       114
           1       0.87      0.51      0.64        65

    accuracy                           0.79       179
   macro avg       0.82      0.73      0.75       179
weighted avg       0.81      0.79      0.78       179